// examples/framework-starters/solid/src/index.jsx
import { render } from 'solid-js/web';
import { version, getComponentPath } from '@tejas-mk2/animation';
import './style.css';

function App() { return <main><h1>ANIMATION + Solid</h1><p>v{version} · {getComponentPath('magneticButton')}</p><button class="animation-button">Animate</button></main>; }
render(() => <App />, document.getElementById('root'));

// examples/framework-starters/react/src/main.jsx
import React from 'react';
import { createRoot } from 'react-dom/client';
import { version, getComponentPath } from '@tejas-mk2/animation';
import './style.css';

function App() {
  return <main><h1>ANIMATION + React</h1><p>v{version} · {getComponentPath('magneticButton')}</p><button className="animation-button">Animate</button></main>;
}

createRoot(document.getElementById('root')).render(<App />);
